#eureka config
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

eureka.instance.prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
management.tracing.sampling.probability: 1.0
spring.zipkin.baseUrl: http://localhost:9411
